// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzP0ECpqi_Zhq8cgmIWg31rnDL8mMz1OY',
    appId: '1:822296666178:web:d0c8cb47de42a643918ddb',
    messagingSenderId: '822296666178',
    projectId: 'falconbytesolutions',
    authDomain: 'falconbytesolutions.firebaseapp.com',
    storageBucket: 'falconbytesolutions.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoaP3U4h6Qkh1dO5-83bDvKel6cU9EWVQ',
    appId: '1:822296666178:android:8504f4026641587c918ddb',
    messagingSenderId: '822296666178',
    projectId: 'falconbytesolutions',
    storageBucket: 'falconbytesolutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_RIdRnTxrxqGHvIPtDIiGdpuh6rsrh8',
    appId: '1:822296666178:ios:097cb1173424fa89918ddb',
    messagingSenderId: '822296666178',
    projectId: 'falconbytesolutions',
    storageBucket: 'falconbytesolutions.appspot.com',
    iosBundleId: 'com.fbportfolio.falconbytesolutinosportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_RIdRnTxrxqGHvIPtDIiGdpuh6rsrh8',
    appId: '1:822296666178:ios:097cb1173424fa89918ddb',
    messagingSenderId: '822296666178',
    projectId: 'falconbytesolutions',
    storageBucket: 'falconbytesolutions.appspot.com',
    iosBundleId: 'com.fbportfolio.falconbytesolutinosportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzP0ECpqi_Zhq8cgmIWg31rnDL8mMz1OY',
    appId: '1:822296666178:web:9621347ac573227b918ddb',
    messagingSenderId: '822296666178',
    projectId: 'falconbytesolutions',
    authDomain: 'falconbytesolutions.firebaseapp.com',
    storageBucket: 'falconbytesolutions.appspot.com',
  );
}
